// Generated by delombok at Sun May 08 23:43:46 EDT 2016
package com.medcognize.view.crud;

import com.medcognize.domain.FamilyMember;
import com.medcognize.domain.User;
import com.medcognize.form.FamilyMemberForm;
import com.medcognize.util.DbUtil;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.spring.annotation.SpringView;
import java.util.Collection;

@SpringView(name = FamilyMemberView.NAME)
public class FamilyMemberView extends CrudView<FamilyMember> {
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(FamilyMemberView.class);
	public static final String NAME = "family";

	public FamilyMemberView() {
		super(FamilyMember.class, "Family Members", new FamilyMemberTable(FamilyMemberForm.class, null));
		User owner = DbUtil.getLoggedInUser();
		if (null == owner) {
			log.error("owner should not be null here");
			return;
		}
		Collection<FamilyMember> members = owner.getRepo().getAll(owner, FamilyMember.class);
		setData(members, owner);
	}

	@Override
	public void enter(ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);
		if (showHeader) {
			toolbar.showAddNewButton();
		}
	}
}
