// Generated by delombok at Sun May 08 23:43:46 EDT 2016
package com.medcognize.view.crud;

import com.medcognize.UserService;
import com.medcognize.domain.Provider;
import com.medcognize.domain.User;
import com.medcognize.form.ProviderForm;
import com.medcognize.util.DbUtil;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.spring.annotation.SpringView;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.ArrayList;
import java.util.Collection;

@SpringView(name = ProviderView.NAME)
public class ProviderView extends CrudView<Provider> {
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ProviderView.class);
	public static final String NAME = "provider";
	private final UserService repo;
	static final ArrayList<String> pids = new ArrayList<String>() {
		{
			add("providerName");
			add("providerType");
			add("providerInPlan");
		}
	};

	@Autowired
	public ProviderView(UserService repo) {
		super(Provider.class, "Providers", new ProviderTable(ProviderForm.class, pids));
		this.repo = repo;
		User owner = DbUtil.getLoggedInUser();
		if (null == owner) {
			log.error("owner should not be null here");
			return;
		}
		Collection<Provider> providers = repo.getAll(owner, Provider.class);
		setData(providers, owner);
	}

	@Override
	public void enter(ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);
		if (showHeader) {
			toolbar.showAddNewButton();
		}
	}
}
