// Generated by delombok at Sun May 08 23:43:45 EDT 2016
package com.medcognize.domain;

import com.google.common.collect.BiMap;
import com.medcognize.MedcognizeUI;
import com.medcognize.domain.basic.DisplayFriendlyAbstractEntity;
import com.medcognize.domain.validator.jsr303.DateFieldInYear;
import com.medcognize.domain.validator.jsr303.DateFieldOnOrAfter;
import org.csveed.annotations.CsvDate;
import org.hibernate.validator.constraints.NotBlank;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.vaadin.addon.daterangefield.DateUtil;
import javax.persistence.Entity;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import java.io.Serializable;
import java.util.Date;
// Two FSAs are equal if they have the same name. FSA Name is unique.
@DateFieldOnOrAfter(first = "fsaEndDate", second = "fsaStartDate", message = "The end date must be equal to or after the start date")
@DateFieldInYear.List({@DateFieldInYear(dateField = "fsaStartDate", yearField = "fsaYear", message = "The start date is not in the year of the FSA"), @DateFieldInYear(dateField = "fsaEndDate", yearField = "fsaYear", message = "The end date is not in the year of the FSA")})
@Entity
public class Fsa extends DisplayFriendlyAbstractEntity implements Serializable {
	//Objectify will not persist static fields, final fields, or fields annotated with @Ignore. It will persist fields
	// with the transient keyword, which only affects serialization.
	private static final Logger LOGGER = LoggerFactory.getLogger(Fsa.class);
	private static final String captionString = "fsaName:FSA Name, amountInFsa:Amount In FSA, fsaYear:Year, fsaStartDate:Period Start, fsaEndDate:Period End";
	@SuppressWarnings("UnusedDeclaration")
	public static final BiMap<String, String> captionMap = createBiMap(captionString);
	@NotBlank(message = "The FSA name cannot be blank")
	private String fsaName = "";
	@Min(0)
	private double amountInFsa = 0.0;
	@Min(value = 2012, message = "Year cannot be before 2012")
	@Max(value = 2020, message = "Year cannot be after 2020")
	private int fsaYear = DateUtil.currentYear();
	@CsvDate(format = MedcognizeUI.US_DATE_FORMAT)
	private Date fsaStartDate = DateUtil.firstDayOfYear(DateUtil.currentYear());
	@CsvDate(format = MedcognizeUI.US_DATE_FORMAT)
	private Date fsaEndDate = DateUtil.lastDayOfYear(DateUtil.currentYear());

	@Override
	public String toString() {
		return fsaName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getFsaName() {
		return this.fsaName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public double getAmountInFsa() {
		return this.amountInFsa;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getFsaYear() {
		return this.fsaYear;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Date getFsaStartDate() {
		return this.fsaStartDate;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Date getFsaEndDate() {
		return this.fsaEndDate;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setFsaName(final String fsaName) {
		this.fsaName = fsaName;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAmountInFsa(final double amountInFsa) {
		this.amountInFsa = amountInFsa;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setFsaYear(final int fsaYear) {
		this.fsaYear = fsaYear;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setFsaStartDate(final Date fsaStartDate) {
		this.fsaStartDate = fsaStartDate;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setFsaEndDate(final Date fsaEndDate) {
		this.fsaEndDate = fsaEndDate;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Fsa() {
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Fsa)) return false;
		final Fsa other = (Fsa) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$fsaName = this.getFsaName();
		final java.lang.Object other$fsaName = other.getFsaName();
		if (this$fsaName == null ? other$fsaName != null : !this$fsaName.equals(other$fsaName)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Fsa;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $fsaName = this.getFsaName();
		result = result * PRIME + ($fsaName == null ? 43 : $fsaName.hashCode());
		return result;
	}
}
