// Generated by delombok at Sun May 08 23:43:45 EDT 2016
package com.medcognize;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class MedcognizeApplication {
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(MedcognizeApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(MedcognizeApplication.class);
    }

    @Bean
    public CommandLineRunner loadData(UserService repo) {
        return new CommandLineRunner() {
            @Override
            public void run(String... args) throws Exception {
                String profile = System.getProperty("spring.profiles.active");
                log.warn("spring.profiles.active --> " + profile + " (if null then profile is default)");
            }
        };
    }
}
