CREATE TABLE contact_info (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version      INTEGER,
  address1     VARCHAR(255),
  address2     VARCHAR(255),
  city         VARCHAR(255),
  phone_number VARCHAR(255),
  state        VARCHAR(255),
  website      VARCHAR(255),
  zip          VARCHAR(255),
  PRIMARY KEY (id)
);
CREATE TABLE family_member (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version            INTEGER,
  family_member_name VARCHAR(255) NOT NULL,
  user_id            BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE fsa (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version        INTEGER,
  amount_in_fsa  DOUBLE       NOT NULL CHECK (amount_in_fsa >= 0),
  fsa_end_date   TIMESTAMP,
  fsa_name       VARCHAR(255) NOT NULL,
  fsa_start_date TIMESTAMP,
  fsa_year       INTEGER      NOT NULL CHECK (fsa_year <= 2020 AND fsa_year >= 2012),
  user_id        BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE medical_expense (
  id                         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version                    INTEGER,
  comments                   VARCHAR(255),
  copay_amount               DOUBLE  NOT NULL CHECK (copay_amount >= 0),
  cost_according_to_provider DOUBLE  NOT NULL CHECK (cost_according_to_provider >= 0),
  DATE                       TIMESTAMP,
  deductible_amount          DOUBLE  NOT NULL CHECK (deductible_amount >= 0),
  maximum_amount             DOUBLE  NOT NULL CHECK (maximum_amount >= 0),
  medical_expense_in_plan    BOOLEAN NOT NULL,
  medical_expense_type       INTEGER,
  out_of_pocket_amount       DOUBLE  NOT NULL CHECK (out_of_pocket_amount >= 0),
  payment_amount             DOUBLE  NOT NULL CHECK (payment_amount >= 0),
  prescription_tier_type     INTEGER,
  family_member_id           BIGINT,
  plan_id                    BIGINT,
  provider_id                BIGINT,
  user_id                    BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE plan (
  id                                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version                              INTEGER,
  active_plan                          BOOLEAN     NOT NULL,
  emergency_room_copay                 DOUBLE      NOT NULL CHECK (emergency_room_copay >= 0),
  family_in_network_deductible         DOUBLE      NOT NULL CHECK (family_in_network_deductible >= 0),
  family_out_of_network_deductible     DOUBLE      NOT NULL CHECK (family_out_of_network_deductible >= 0),
  family_out_of_pocket_limit           DOUBLE      NOT NULL CHECK (family_out_of_pocket_limit >= 0),
  individual_in_network_deductible     DOUBLE      NOT NULL CHECK (individual_in_network_deductible >= 0),
  individual_out_of_network_deductible DOUBLE      NOT NULL CHECK (individual_out_of_network_deductible >= 0),
  individual_out_of_pocket_limit       DOUBLE      NOT NULL CHECK (individual_out_of_pocket_limit >= 0),
  notes                                VARCHAR(255),
  plan_end_date                        TIMESTAMP,
  plan_name                            VARCHAR(50) NOT NULL,
  plan_start_date                      TIMESTAMP,
  plan_type                            INTEGER     NOT NULL,
  plan_year                            INTEGER     NOT NULL CHECK (plan_year >= 2012 AND plan_year <= 2020),
  primary_care_copay                   DOUBLE      NOT NULL CHECK (primary_care_copay >= 0),
  specialist_copay                     DOUBLE      NOT NULL CHECK (specialist_copay >= 0),
  tier1prescription_copay              DOUBLE      NOT NULL CHECK (tier1prescription_copay >= 0),
  tier2prescription_copay              DOUBLE      NOT NULL CHECK (tier2prescription_copay >= 0),
  tier3prescription_copay              DOUBLE      NOT NULL CHECK (tier3prescription_copay >= 0),
  user_id                              BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE plan_limit (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version      INTEGER,
  annual_limit DOUBLE NOT NULL,
  balance      DOUBLE NOT NULL,
  limit_name   VARCHAR(255),
  usage        DOUBLE NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE provider (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version          INTEGER,
  provider_id      VARCHAR(255),
  provider_in_plan BOOLEAN      NOT NULL,
  provider_name    VARCHAR(255) NOT NULL,
  provider_type    INTEGER,
  user_id          BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE provider_locations (
  provider_id  BIGINT NOT NULL,
  locations_id BIGINT NOT NULL
);
CREATE TABLE user (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version                 INTEGER,
  account_non_expired     BOOLEAN NOT NULL,
  account_non_locked      BOOLEAN NOT NULL,
  credentials_non_expired BOOLEAN NOT NULL,
  enabled                 BOOLEAN NOT NULL,
  first_name              VARCHAR(255),
  last_name               VARCHAR(255),
  password                VARCHAR(255),
  username                VARCHAR(255),
  PRIMARY KEY (id)
);
CREATE TABLE user_user_roles (
  user_id    BIGINT NOT NULL,
  user_roles VARCHAR(255)
);
ALTER TABLE provider_locations
  ADD CONSTRAINT UK_59011c7q5x5rcn0ath0rb9s6c UNIQUE (locations_id);
ALTER TABLE user
  ADD CONSTRAINT UK_sb8bbouer5wak8vyiiy4pf2bx UNIQUE (username);
ALTER TABLE family_member
  ADD CONSTRAINT FK_7ldr00f9kc7jydj38i3ie72yx FOREIGN KEY (user_id) REFERENCES user;
ALTER TABLE fsa
  ADD CONSTRAINT FK_3u07bbpspx10vph4q3mm8yh03 FOREIGN KEY (user_id) REFERENCES user;
ALTER TABLE medical_expense
  ADD CONSTRAINT FK_pxsv2lil01yks1jmrg55eb23s FOREIGN KEY (user_id) REFERENCES user;
ALTER TABLE plan
  ADD CONSTRAINT FK_3o180e1ld6dth3jxbl5a79tsl FOREIGN KEY (user_id) REFERENCES user;
ALTER TABLE provider
  ADD CONSTRAINT FK_8oc1o2uw5cl4vnitihnb5dfi5 FOREIGN KEY (user_id) REFERENCES user;
ALTER TABLE provider_locations
  ADD CONSTRAINT FK_59011c7q5x5rcn0ath0rb9s6c FOREIGN KEY (locations_id) REFERENCES contact_info;
ALTER TABLE provider_locations
  ADD CONSTRAINT FK_im4hdvxrpqd6e6n05x0kn7hdm FOREIGN KEY (provider_id) REFERENCES provider;
ALTER TABLE user_user_roles
  ADD CONSTRAINT FK_736t3ni8pqcolkkkpmlt6a3xi FOREIGN KEY (user_id) REFERENCES user;