// Generated by delombok at Sun May 08 23:43:46 EDT 2016
package com.medcognize.util.export;

import org.csveed.api.Header;
import org.csveed.bean.ColumnNameMapper;
import org.csveed.common.Column;
import org.csveed.report.CsvException;

public class TolerantColumnNameMapper<T> extends ColumnNameMapper<T> {
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(TolerantColumnNameMapper.class);

    @Override
    protected void checkKey(Header header, Column key) {
        try {
            header.getIndex(key.getColumnName());
        } catch (CsvException err) {
            TolerantColumnNameMapper.log.warn("In class " + this.beanInstructions.getBeanClass().getSimpleName() + " -- This is probably a new " + "field.  Issue will go away when CSV file is persisted.");
        }
    }
}
